style_edition = "2024"
group_imports = "StdExternalCrate"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
imports_granularity = "Crate"
reorder_impl_items = true
use_field_init_shorthand = true
