[package]
name = "sundae-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
itertools = "0.10.5"
llvm-sys = { version = "170.0.0", features = ["prefer-static"] }
tabled = "0.12.2"
