[package]
name = "sundae-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
itertools = "0.10.5"
tabled = "0.12.2"
inkwell = { version = "0.2.0", features = ["llvm16-0"] }
